version: '3'

services:

  db:
    container_name: db
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: olympics
    ports:
      - "3306:3306"
    volumes:
      - ./olympics-db/olympics-ddl.sql:/docker-entrypoint-initdb.d/olympics-ddl.sql
      - ./olympics-db/olympics-dml.sql:/docker-entrypoint-initdb.d/olympics-dml.sql
      # - data:/var/lib/mysql

  app:
    build: .
    container_name: app
    image: app
    command: streamlit run /app/app.py
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app

# volumes:
#   data: