INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GIZ', 'Country 1', 375, 24);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('QMM', 'Country 2', 47, 116);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('RWH', 'Country 3', 135, 32);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('SUL', 'Country 4', 376, 67);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('BFE', 'Country 5', 294, 35);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('XKV', 'Country 6', 27, 79);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('DZW', 'Country 7', 198, 111);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('MQK', 'Country 8', 417, 19);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('KFK', 'Country 9', 452, 7);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ESF', 'Country 10', 474, 27);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WVI', 'Country 11', 210, 86);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UFW', 'Country 12', 78, 9);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WQN', 'Country 13', 316, 145);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('EEW', 'Country 14', 62, 56);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WQY', 'Country 15', 205, 76);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('RZK', 'Country 16', 108, 65);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('QAK', 'Country 17', 266, 104);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('CVL', 'Country 18', 291, 22);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('HYB', 'Country 19', 100, 74);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GAY', 'Country 20', 89, 52);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WHJ', 'Country 21', 347, 106);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('KJP', 'Country 22', 416, 25);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('TPG', 'Country 23', 313, 80);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('DED', 'Country 24', 491, 2);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ZJC', 'Country 25', 424, 26);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('KIA', 'Country 26', 465, 58);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('IKS', 'Country 27', 486, 43);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('YMA', 'Country 28', 170, 86);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('PSA', 'Country 29', 273, 90);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GQV', 'Country 30', 99, 32);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UOD', 'Country 31', 329, 7);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('DWV', 'Country 32', 140, 75);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('FUK', 'Country 33', 439, 20);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('LYC', 'Country 34', 25, 144);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('TJV', 'Country 35', 395, 59);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UWK', 'Country 36', 428, 69);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('AUJ', 'Country 37', 12, 138);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GZS', 'Country 38', 352, 79);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ALY', 'Country 39', 190, 47);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GRK', 'Country 40', 333, 21);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UPH', 'Country 41', 367, 81);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ACI', 'Country 42', 299, 147);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('TLU', 'Country 43', 168, 80);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('EFG', 'Country 44', 140, 79);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('YNV', 'Country 45', 135, 35);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('QNY', 'Country 46', 169, 0);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GZT', 'Country 47', 87, 87);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('OUM', 'Country 48', 13, 116);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('DYR', 'Country 49', 188, 145);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('EDP', 'Country 50', 230, 18);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('FUL', 'Country 51', 6, 118);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('NWT', 'Country 52', 222, 84);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('XQV', 'Country 53', 195, 39);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ETV', 'Country 54', 342, 91);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('VDA', 'Country 55', 49, 38);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WMK', 'Country 56', 407, 134);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('HDR', 'Country 57', 490, 41);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('IGR', 'Country 58', 18, 18);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WSD', 'Country 59', 102, 6);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('BET', 'Country 60', 402, 81);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('DVX', 'Country 61', 384, 139);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('BHL', 'Country 62', 201, 100);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('BXI', 'Country 63', 40, 137);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('LZT', 'Country 64', 288, 53);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('OMY', 'Country 65', 347, 129);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('XHW', 'Country 66', 236, 76);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('CUO', 'Country 67', 128, 21);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UCH', 'Country 68', 399, 18);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('KWX', 'Country 69', 72, 5);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GRC', 'Country 70', 309, 24);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('IXT', 'Country 71', 353, 11);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('SZI', 'Country 72', 324, 15);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ZJK', 'Country 73', 334, 67);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('HBZ', 'Country 74', 54, 17);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('JGM', 'Country 75', 486, 93);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('RQV', 'Country 76', 422, 145);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('GYA', 'Country 77', 265, 91);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('EYX', 'Country 78', 188, 123);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('TJF', 'Country 79', 345, 37);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ZXS', 'Country 80', 422, 28);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('MWM', 'Country 81', 49, 125);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('HQZ', 'Country 82', 230, 58);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WCY', 'Country 83', 431, 138);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('AYM', 'Country 84', 32, 96);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('QFB', 'Country 85', 88, 99);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('JXU', 'Country 86', 466, 98);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('MHX', 'Country 87', 105, 60);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('MVV', 'Country 88', 53, 110);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('VYZ', 'Country 89', 458, 141);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('CXK', 'Country 90', 484, 40);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('KPY', 'Country 91', 271, 12);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('ZOC', 'Country 92', 4, 83);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('CWA', 'Country 93', 84, 9);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('WSA', 'Country 94', 273, 116);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('RIK', 'Country 95', 404, 87);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('RQE', 'Country 96', 80, 9);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('IKL', 'Country 97', 191, 97);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('UQS', 'Country 98', 177, 32);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('VEM', 'Country 99', 417, 101);
INSERT INTO Country (NOC, name, athletesNr, medalsNr) VALUES ('QFR', 'Country 100', 171, 107);
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 1');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 2');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 3');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 4');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 5');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 6');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 7');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 8');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 9');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 10');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 11');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 12');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 13');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 14');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 15');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 16');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 17');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 18');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 19');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 20');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 21');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 22');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 23');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 24');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 25');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 26');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 27');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 28');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 29');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 30');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 31');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 32');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 33');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 34');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 35');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 36');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 37');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 38');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 39');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 40');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 41');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 42');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 43');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 44');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 45');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 46');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 47');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 48');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 49');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 50');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 51');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 52');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 53');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 54');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 55');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 56');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 57');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 58');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 59');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 60');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 61');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 62');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 63');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 64');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 65');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 66');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 67');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 68');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 69');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 70');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 71');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 72');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 73');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 74');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 75');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 76');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 77');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 78');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 79');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 80');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 81');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 82');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 83');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 84');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 85');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 86');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 87');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 88');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 89');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 90');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 91');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 92');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 93');
INSERT INTO Discipline (category, name) VALUES ('Track and Field', 'Discipline 94');
INSERT INTO Discipline (category, name) VALUES ('Archery', 'Discipline 95');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 96');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 97');
INSERT INTO Discipline (category, name) VALUES ('Gymnastics', 'Discipline 98');
INSERT INTO Discipline (category, name) VALUES ('Cycling', 'Discipline 99');
INSERT INTO Discipline (category, name) VALUES ('Swimming', 'Discipline 100');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (52, '2023-08-25', 'City 1', 48, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (67, '2023-10-20', 'City 2', 40, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (48, '2023-05-05', 'City 3', 42, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (51, '2023-03-18', 'City 4', 43, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (20, '2023-11-26', 'City 5', 19, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (25, '2023-08-27', 'City 6', 6, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (22, '2023-08-19', 'City 7', 43, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (73, '2023-12-15', 'City 8', 24, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (1, '2023-04-29', 'City 9', 32, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (50, '2023-09-25', 'City 10', 46, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (68, '2023-01-02', 'City 11', 10, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (69, '2023-03-21', 'City 12', 42, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (22, '2023-10-17', 'City 13', 50, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (23, '2023-04-11', 'City 14', 28, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (7, '2023-12-29', 'City 15', 33, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (39, '2023-05-08', 'City 16', 13, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (91, '2023-12-17', 'City 17', 40, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (95, '2023-07-09', 'City 18', 44, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (66, '2023-09-16', 'City 19', 19, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (23, '2023-08-24', 'City 20', 21, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (38, '2023-07-25', 'City 21', 40, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (35, '2023-11-20', 'City 22', 8, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (69, '2023-03-20', 'City 23', 36, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (8, '2023-10-12', 'City 24', 27, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (54, '2023-12-02', 'City 25', 28, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (67, '2023-08-21', 'City 26', 35, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (99, '2023-05-18', 'City 27', 50, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (10, '2023-03-05', 'City 28', 18, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (37, '2023-09-12', 'City 29', 2, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (75, '2023-04-15', 'City 30', 23, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (42, '2023-03-26', 'City 31', 18, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (42, '2023-07-06', 'City 32', 26, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (5, '2023-08-29', 'City 33', 45, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (60, '2023-01-07', 'City 34', 16, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (30, '2023-07-16', 'City 35', 1, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (79, '2023-10-12', 'City 36', 2, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (70, '2023-03-13', 'City 37', 4, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (60, '2023-12-18', 'City 38', 22, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (45, '2023-08-20', 'City 39', 43, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (65, '2023-04-26', 'City 40', 29, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (55, '2023-07-18', 'City 41', 19, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (36, '2023-01-25', 'City 42', 19, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (9, '2023-04-01', 'City 43', 35, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (4, '2023-06-25', 'City 44', 5, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (73, '2023-08-25', 'City 45', 21, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (80, '2023-09-11', 'City 46', 45, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (26, '2023-02-21', 'City 47', 13, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (38, '2023-02-11', 'City 48', 28, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (97, '2023-05-18', 'City 49', 42, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (24, '2023-12-06', 'City 50', 7, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (57, '2023-06-13', 'City 51', 32, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (15, '2023-05-30', 'City 52', 4, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (99, '2023-08-22', 'City 53', 24, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (45, '2023-03-27', 'City 54', 2, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (15, '2023-09-27', 'City 55', 23, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (43, '2023-03-20', 'City 56', 16, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (23, '2023-04-16', 'City 57', 6, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (61, '2023-03-15', 'City 58', 14, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (45, '2023-09-07', 'City 59', 42, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (6, '2023-12-19', 'City 60', 5, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (44, '2023-09-19', 'City 61', 9, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (44, '2023-12-06', 'City 62', 47, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (54, '2023-02-13', 'City 63', 45, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (26, '2023-04-09', 'City 64', 43, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (75, '2023-03-30', 'City 65', 39, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (87, '2023-11-07', 'City 66', 29, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (73, '2023-11-21', 'City 67', 26, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (98, '2023-03-07', 'City 68', 48, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (47, '2023-09-15', 'City 69', 17, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (4, '2023-03-20', 'City 70', 50, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (26, '2023-12-03', 'City 71', 13, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (19, '2023-04-20', 'City 72', 7, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (25, '2023-09-02', 'City 73', 6, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (74, '2023-09-22', 'City 74', 19, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (45, '2023-10-17', 'City 75', 22, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (5, '2023-08-31', 'City 76', 46, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (98, '2023-07-10', 'City 77', 30, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (22, '2023-04-17', 'City 78', 11, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (71, '2023-02-07', 'City 79', 30, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (80, '2023-04-15', 'City 80', 2, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (33, '2023-08-11', 'City 81', 34, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (1, '2023-04-17', 'City 82', 7, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (47, '2023-02-08', 'City 83', 9, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (38, '2023-11-16', 'City 84', 20, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (52, '2023-11-10', 'City 85', 30, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (26, '2023-01-13', 'City 86', 45, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (46, '2023-12-04', 'City 87', 13, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (8, '2023-07-01', 'City 88', 23, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (24, '2023-07-30', 'City 89', 27, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (73, '2023-04-29', 'City 90', 9, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (99, '2023-03-09', 'City 91', 50, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (32, '2023-05-27', 'City 92', 31, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (47, '2023-06-30', 'City 93', 44, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (22, '2023-06-07', 'City 94', 3, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (83, '2023-03-11', 'City 95', 47, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (89, '2023-09-18', 'City 96', 12, 'Heat');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (96, '2023-02-26', 'City 97', 1, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (42, '2023-12-03', 'City 98', 1, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (95, '2023-05-04', 'City 99', 1, 'Final');
INSERT INTO Contest (idDiscipline, date, place, athletesNr, nature) VALUES (52, '2023-04-02', 'City 100', 16, 'Final');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 1', 'Surname 1', 'NB', 'RAL');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 2', 'Surname 2', 'M', 'LLS');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 3', 'Surname 3', 'NB', 'UJT');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 4', 'Surname 4', 'F', 'GHX');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 5', 'Surname 5', 'M', 'NJR');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 6', 'Surname 6', 'F', 'ZKA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 7', 'Surname 7', 'F', 'RXM');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 8', 'Surname 8', 'F', 'CPL');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 9', 'Surname 9', 'F', 'CJQ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 10', 'Surname 10', 'NB', 'NXB');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 11', 'Surname 11', 'F', 'PHB');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 12', 'Surname 12', 'F', 'DXR');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 13', 'Surname 13', 'F', 'WYE');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 14', 'Surname 14', 'F', 'LKO');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 15', 'Surname 15', 'M', 'HTM');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 16', 'Surname 16', 'M', 'NBE');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 17', 'Surname 17', 'M', 'IZP');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 18', 'Surname 18', 'F', 'RNL');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 19', 'Surname 19', 'M', 'HSY');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 20', 'Surname 20', 'F', 'IBY');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 21', 'Surname 21', 'M', 'GYF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 22', 'Surname 22', 'F', 'FYC');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 23', 'Surname 23', 'F', 'EYR');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 24', 'Surname 24', 'F', 'QIP');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 25', 'Surname 25', 'NB', 'OMO');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 26', 'Surname 26', 'F', 'MRU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 27', 'Surname 27', 'M', 'RDX');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 28', 'Surname 28', 'F', 'MKT');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 29', 'Surname 29', 'F', 'HXN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 30', 'Surname 30', 'F', 'LFC');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 31', 'Surname 31', 'NB', 'ROF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 32', 'Surname 32', 'M', 'MXY');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 33', 'Surname 33', 'NB', 'QLZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 34', 'Surname 34', 'M', 'MRN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 35', 'Surname 35', 'F', 'CWF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 36', 'Surname 36', 'NB', 'RQQ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 37', 'Surname 37', 'F', 'HXJ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 38', 'Surname 38', 'M', 'ZST');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 39', 'Surname 39', 'F', 'LIK');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 40', 'Surname 40', 'M', 'UEV');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 41', 'Surname 41', 'F', 'JAU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 42', 'Surname 42', 'NB', 'YDZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 43', 'Surname 43', 'M', 'YHI');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 44', 'Surname 44', 'F', 'COM');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 45', 'Surname 45', 'NB', 'QMO');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 46', 'Surname 46', 'F', 'WFA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 47', 'Surname 47', 'F', 'AES');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 48', 'Surname 48', 'F', 'IPR');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 49', 'Surname 49', 'NB', 'TSV');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 50', 'Surname 50', 'NB', 'RHN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 51', 'Surname 51', 'NB', 'JYR');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 52', 'Surname 52', 'NB', 'RAQ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 53', 'Surname 53', 'NB', 'DCC');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 54', 'Surname 54', 'F', 'UMK');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 55', 'Surname 55', 'M', 'GDG');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 56', 'Surname 56', 'NB', 'PAA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 57', 'Surname 57', 'NB', 'QMM');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 58', 'Surname 58', 'F', 'FYJ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 59', 'Surname 59', 'M', 'QUI');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 60', 'Surname 60', 'M', 'XWP');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 61', 'Surname 61', 'NB', 'DGH');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 62', 'Surname 62', 'NB', 'YBP');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 63', 'Surname 63', 'F', 'STF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 64', 'Surname 64', 'NB', 'MTZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 65', 'Surname 65', 'F', 'UJG');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 66', 'Surname 66', 'M', 'VVZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 67', 'Surname 67', 'M', 'IIP');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 68', 'Surname 68', 'NB', 'QDW');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 69', 'Surname 69', 'M', 'JWA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 70', 'Surname 70', 'F', 'RPC');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 71', 'Surname 71', 'M', 'RXW');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 72', 'Surname 72', 'M', 'UAJ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 73', 'Surname 73', 'F', 'OVO');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 74', 'Surname 74', 'NB', 'BUN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 75', 'Surname 75', 'F', 'KDZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 76', 'Surname 76', 'NB', 'ERF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 77', 'Surname 77', 'NB', 'SVS');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 78', 'Surname 78', 'F', 'CCV');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 79', 'Surname 79', 'M', 'HTD');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 80', 'Surname 80', 'NB', 'OQZ');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 81', 'Surname 81', 'M', 'BYL');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 82', 'Surname 82', 'F', 'ZTI');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 83', 'Surname 83', 'M', 'CQF');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 84', 'Surname 84', 'NB', 'JSA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 85', 'Surname 85', 'NB', 'CAU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 86', 'Surname 86', 'M', 'FIV');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 87', 'Surname 87', 'NB', 'RZU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 88', 'Surname 88', 'NB', 'HON');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 89', 'Surname 89', 'F', 'VKK');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 90', 'Surname 90', 'NB', 'SRG');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 91', 'Surname 91', 'M', 'IKU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 92', 'Surname 92', 'M', 'HQA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 93', 'Surname 93', 'M', 'OTN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 94', 'Surname 94', 'M', 'CMD');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 95', 'Surname 95', 'M', 'KJS');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 96', 'Surname 96', 'NB', 'EUA');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 97', 'Surname 97', 'M', 'YZT');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 98', 'Surname 98', 'F', 'JZU');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 99', 'Surname 99', 'F', 'XRN');
INSERT INTO Athlete (name, surname, gender, team) VALUES ('Name 100', 'Surname 100', 'M', 'EYK');
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (41, 1, 46);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (46, 85, 3);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (22, 75, 71);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (27, 82, 65);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (45, 25, 69);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (45, 76, 89);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (48, 86, 62);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (70, 40, 47);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (58, 26, 9);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (84, 25, 33);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (91, 64, 42);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (27, 11, 40);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (26, 18, 74);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (18, 27, 18);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (50, 20, 33);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (14, 11, 3);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (89, 1, 14);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (76, 78, 9);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (69, 79, 72);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (44, 88, 100);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (20, 7, 46);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (78, 71, 12);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (18, 59, 25);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (86, 80, 41);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (17, 37, 17);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (47, 44, 87);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (60, 17, 50);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (59, 15, 71);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (81, 36, 100);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (86, 72, 54);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (53, 94, 57);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (21, 2, 62);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (40, 51, 18);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (82, 4, 20);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (61, 13, 29);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (16, 34, 91);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (4, 32, 29);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (44, 1, 60);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (79, 85, 81);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (100, 67, 75);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (8, 93, 19);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (60, 67, 2);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (27, 77, 20);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (50, 2, 12);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (49, 65, 23);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (32, 72, 71);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (31, 33, 13);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (86, 53, 41);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (78, 89, 16);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (1, 13, 81);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (37, 72, 19);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (62, 21, 16);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (26, 22, 70);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (84, 13, 75);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (66, 22, 51);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (4, 30, 39);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (36, 67, 6);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (11, 44, 13);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (56, 69, 94);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (70, 99, 97);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (34, 85, 89);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (26, 59, 69);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (37, 72, 98);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (65, 65, 3);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (80, 85, 90);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (63, 31, 41);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (13, 51, 67);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (41, 45, 52);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (42, 99, 63);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (74, 90, 60);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (86, 94, 43);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (59, 20, 30);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (42, 37, 1);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (65, 43, 32);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (35, 77, 74);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (86, 10, 59);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (36, 100, 50);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (31, 57, 56);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (78, 25, 50);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (7, 54, 36);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (15, 59, 90);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (35, 45, 93);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (22, 44, 57);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (47, 76, 83);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (47, 49, 67);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (43, 73, 31);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (89, 59, 47);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (9, 58, 1);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (98, 17, 32);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (5, 23, 9);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (41, 8, 47);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (100, 71, 90);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (19, 57, 13);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (91, 93, 45);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (38, 70, 1);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (14, 69, 60);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (66, 39, 84);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (94, 47, 74);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (88, 3, 78);
INSERT INTO ContestParticipant (idAthlete, idContest, partRank) VALUES (5, 50, 10);
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (96, 44, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (18, 84, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (39, 78, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (74, 46, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (78, 38, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (22, 1, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (7, 59, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (16, 28, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (92, 38, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (92, 40, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (64, 67, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (50, 31, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (87, 26, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (34, 45, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (99, 64, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (51, 1, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (10, 39, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (26, 30, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (75, 37, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (25, 60, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (45, 71, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (16, 27, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (20, 45, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (52, 39, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (95, 98, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (77, 53, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (41, 85, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (29, 18, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (17, 21, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (9, 79, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (84, 84, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (30, 38, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (79, 92, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (85, 72, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (14, 41, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (24, 87, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (58, 71, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (95, 7, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (55, 38, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (79, 5, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (53, 98, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (63, 70, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (92, 26, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (73, 11, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (64, 74, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (36, 89, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (33, 54, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (10, 17, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (9, 41, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (7, 39, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (28, 46, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (94, 79, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (8, 71, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (9, 56, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (22, 58, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (27, 34, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (86, 80, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (16, 41, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (84, 25, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (45, 14, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (10, 32, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (81, 70, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (59, 100, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (7, 25, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (41, 28, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (38, 42, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (82, 37, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (95, 54, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (4, 54, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (17, 41, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (93, 32, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (21, 36, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (88, 34, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (18, 47, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (24, 31, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (59, 39, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (75, 98, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (32, 21, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (95, 49, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (59, 34, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (6, 53, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (20, 98, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (47, 21, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (30, 56, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (36, 55, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (31, 95, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (7, 80, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (31, 46, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (12, 46, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (6, 48, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (27, 53, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (34, 5, 'Gold');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (11, 49, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (17, 14, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (32, 64, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (64, 41, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (3, 6, 'Silver');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (43, 64, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (69, 39, 'Bronze');
INSERT INTO ContestMedals (idAthlete, idContest, medal) VALUES (40, 2, 'Gold');